"""rename_stripe_to_square_fields

Revision ID: b9cb8680a3c4
Revises: 8269e9e3dae4
Create Date: 2026-10-01 14:37:45.763562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cb8680a3c4'
down_revision: Union[str, Sequence[str], None] = '8269e9e3dae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('square_customer_id', sa.String(), nullable=True))
    op.add_column('memberships', sa.Column('square_order_id', sa.String(), nullable=True))
    op.drop_column('memberships', 'stripe_payment_intent_id')
    op.drop_column('memberships', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True))
    op.add_column('memberships', sa.Column('stripe_payment_intent_id', sa.VARCHAR(), nullable=True))
    op.drop_column('memberships', 'square_order_id')
    op.drop_column('memberships', 'square_customer_id')
    # ### end Alembic commands ###
